### ISSUE TITLE
Unable to play audio off URI

### ISSUE THREAD

**Issue by GroomedGorilla** [MattVador/node-red-contrib-play-sound#2]
I'm trying to use your node to play sound off a URI (e.g. http://egeland.net/pub/ringtones/Mailroom.mp3).

I've tried passing the inputs you've described in your ReadMe as inputs, including a blank payload but haven't had much luck. Each time I try triggering the node I get the follow error in the debug section:

"TypeError: Cannot read property 'pid' of undefined"

as well as a pop-up alert in Node-Red saying "node-red-contrib-play-sound/play-sound:common.notification.error"

I'm only setting the audioURI setting at the moment (with the link mentioned above) without any options. What pid is the script expecting?

**Comment by MattVador** [comment]
Hi,

This behavior looks like of an undefined audioURI parameter. How do you specify the audioURI setting ?
First you should try set the audioURI in the PlaySound node options without input.
Then be careful that the PlaySound node expect the following message : {"payload": "start", "audioURI": "http://egeland.net/pub/ringtones/Mailroom.mp3 "}.
For example {"payload": {"audioURI": "http://egeland.net/pub/ringtones/Mailroom.mp3 "}} will not work.

I suggest you use the audioURI in the PlaySound node options and just send the "start" payload.

**Comment by GroomedGorilla** [comment]
That's exactly how I've got it set up. I've set the audio URI in the PlaySound node settings (double clicking on the node) without setting any other options. Tried triggering it through the PlaySound node itself and another time by injecting a blank payload (which should be the same as "start").

I've now tried connecting an inject node with JSON payload set as 
`[{"payload": "start", "audioURI": "http://egeland.net/pub/ringtones/Mailroom.mp3"}] `
connected to a function node with simply:
`return [msg.payload, msg.audioURI];` then connected to the PlaySound node (with no options set). But having the same issue.

Also tried having the inject node send out a simple "start" straight to the PlaySound node with options set to
`{"audioURI":"http://egeland.net/pub/ringtones/Mailroom.mp3"}`
(I had tried setting it on the audioURI setting within the node but didn't have much luck there either)

No luck in either of these cases though. Still getting the same error mentioned before.

**Comment by GroomedGorilla** [comment]
I've figured out the issue here. The node seems to be looking for one of a list of media players installed on the user's machine. The media player's path also needs to be added to the environment variables on the machine in order to be found.

You might want to update the ReadMe to indicate this as a pre-requisite.
