### ISSUE TITLE
Chaining two occurrences with different "Audio URI"s in the node plays first one twice

### ISSUE THREAD

**Issue by juggledad** [MattVador/node-red-contrib-play-sound#5]
`inject (timestamp) -> Play Audio (Audio URI = test1.wav) -> Play Audio (Audio URI = test2.wav)
`
In this case test1.wav is played twice. Putting a debug to the output of both occurances gets:

> 5/30/2018, 9:04:33 AMnode: d7c52afd.fac4c
> msg : Object
> { _msgid: "c52198df.ca8918", topic: "", payload: "end", audioURI: "/home/pi/test1.wav" }
> 5/30/2018, 9:04:37 AMnode: 587c7b6f.481e24
> msg : Object
> { _msgid: "c52198df.ca8918", topic: "", payload: "end", audioURI: "/home/pi/test1.wav" }
> 

If I use
`inject -> change (set msg.audioURI = test1.wav) -> Play Audio -> change (set msg.audioURI = test2.wav) -> Play Audio 
`or
`inject -> Play Audio (Audio URI = test1.wav) -> change (set msg.audioURI = test2.wav) -> Play Audio 
`
then the two different files play.

**Comment by MattVador** [comment]
Hi juggledad, the ouput message of PlaySound node contain msg.audioURI with the audioURL played.
So when two PlaySound node chained, the first node output msg.audioURI to the second node.

And your test1.wav is played by the two nodes.

**Comment by juggledad** [comment]
But in the description it says 
msg.audioURI: File name or url to play - If empty, then the one in dialog is used
so are you saying that this should say
msg.audioURI: File name or url to play - the one in the dialog will be ignored if this is passed in.

**Comment by MattVador** [comment]
Hi juggledad, sorry for the delay but you are right :

> msg.audioURI: File name or url to play - the one in the dialog will be ignored if this is passed in
