### ISSUE TITLE
How to serve up options to a player (AFPLAY tested)

### ISSUE THREAD

**Issue by juggledad** [MattVador/node-red-contrib-play-sound#6]
This is here so anyone else trying to pass options to 'afplay' will have an easier time than I did (grin). This may hold true to other players also.

AFPLAY has many options. If you were using it a CLI setting you would have something like this:
`afplay -v 0.5 -t 1.0 -r 0.5 -q 0.5 -d /path/to/soundfile.ext`
This says set the volume (-v) to 0.5, play the track for 1 second (-t 1.0), set the speed (-r) to 0.5 (slow), the quality (-q) to .05, debug (-d) and the path to the file:   /path/to/soundfile.ext

The path to the file `/path/to/soundfile.ext` is set in the node's '**Audio URI**' option OR passed to the node in msg.audioURI.

The options (-t, -v etc) are entered in the '**Audio Options**' option OR passed to the node in msg.options as a json object using the format: `{"afplay": [ "-r", 0.5, "-t", 2.5 ] }` 

Other players probably use the same format I haven't tested them.

**Comment by MattVador** [comment]
Hi juggledad, thanks for your tests.
